
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.stone_type]

		[types.stone_type.twilightforest]
			deadrock = true
			mazestone = true

		[types.stone_type.galosphere]
			pink_salt = true
			rose_pink_salt = true
			pastel_pink_salt = true

		[types.stone_type.create]
			limestone = true
			asurine = true
			crimsite = true
			ochrum = true
			veridium = true
			scoria = true
			scorchia = true

		[types.stone_type.deep_aether]
			clorite = true
			raw_clorite = true
			aseterite = true

		[types.stone_type.quark]
			soul_sandstone = true
			limestone = true
			jasper = true
			shale = true
			myalite = true
			permafrost = true

		[types.stone_type.regions_unexplored]
			argillite = true
			chalk = true

		[types.stone_type.cavesanddepths]
			slate = true
			chert = true

		[types.stone_type.burnt]
			sooty_stone = true

		[types.stone_type.tconstruct]
			seared_stone = true
			scorched_stone = true

		[types.stone_type.terramity]
			igneostone = true
			moonstone = true

		[types.stone_type.aether]
			holystone = true

		[types.stone_type.iceandfire]
			dread_stone = true

		[types.stone_type.caverns_and_chasms]
			sugilite = true

		[types.stone_type.alexscaves]
			galena = true
			radrock = true
			abyssmarine = true
			guanostone = true

		[types.stone_type.natures_spirit]
			white_kaolin = true
			light_gray_kaolin = true
			gray_kaolin = true
			black_kaolin = true
			brown_kaolin = true
			red_kaolin = true
			orange_kaolin = true
			yellow_kaolin = true
			lime_kaolin = true
			green_kaolin = true
			cyan_kaolin = true
			light_blue_kaolin = true
			blue_kaolin = true
			purple_kaolin = true
			magenta_kaolin = true
			pink_kaolin = true
			pink_sandstone = true
			white_chalk = true
			light_gray_chalk = true
			gray_chalk = true
			black_chalk = true
			brown_chalk = true
			red_chalk = true
			orange_chalk = true
			yellow_chalk = true
			lime_chalk = true
			green_chalk = true
			cyan_chalk = true
			light_blue_chalk = true
			blue_chalk = true
			purple_chalk = true
			magenta_chalk = true
			pink_chalk = true
			travertine = true
			chert = true
			kaolin = true

	[types.mud_type]

		[types.mud_type.deep_aether]
			aether_mud = true

	[types.wood_type]

		[types.wood_type.burnt]
			smoldering_bamboo = true
			burnt = true
			smoldering = true
			burnt_bamboo = true
			ember = true
			sooty_oak = true
			sooty_dark_oak = true
			sooty_spruce = true
			sooty_birch = true
			sooty_acacia = true
			sooty_mangrove = true
			sooty_cherry = true
			sooty_jungle = true
			blazing = true
			smoldering_soul = true
			burnt_soul = true

		[types.wood_type.caverns_and_chasms]
			azalea = true

		[types.wood_type.domum_ornamentum]
			cactus = true
			cactus_extra = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.valhelsia_structures]
			lapidified_jungle = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.tconstruct]
			greenheart = true
			skyroot = true
			bloodshroom = true
			enderbark = true

		[types.wood_type.aether]
			skyroot = true

		[types.wood_type.deep_aether]
			roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.wood_type.dungeons_and_combat]
			elden_oak = true

		[types.wood_type.iceandfire]
			dreadwood = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.wood_type.autumnity]
			maple = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

		[types.wood_type.regions_unexplored]
			alpha = true
			baobab = true
			blackwood = true
			blue_bioshroom = true
			brimwood = true
			cobalt = true
			cypress = true
			dead = true
			eucalyptus = true
			green_bioshroom = true
			joshua = true
			kapok = true
			larch = true
			magnolia = true
			maple = true
			mauve = true
			palm = true
			pine = true
			pink_bioshroom = true
			redwood = true
			socotra = true
			willow = true
			yellow_bioshroom = true

		[types.wood_type.dungeonnowloading]
			azuro_oak = true

		[types.wood_type.the_great_outdoors]
			whitebark_pine = true

		[types.wood_type.natures_spirit]
			redwood = true
			sugi = true
			wisteria = true
			fir = true
			willow = true
			aspen = true
			maple = true
			cypress = true
			olive = true
			joshua = true
			ghaf = true
			palo_verde = true
			coconut = true
			cedar = true
			larch = true
			mahogany = true
			saxaul = true

	[types.leaves_type]

		[types.leaves_type.burnt]
			burnt = true
			smoldering = true
			smoldering_oak = true
			smoldering_dark_oak = true
			smoldering_spruce = true
			smoldering_birch = true
			smoldering_jungle = true
			smoldering_mangrove = true
			smoldering_cherry = true
			smoldering_acacia = true
			burnt_soul = true
			soul_acacia = true
			soul_oak = true
			soul_spruce = true
			soul_birch = true
			soul_jungle = true
			soul_mangrove = true
			soul_cherry = true
			blast = true

		[types.leaves_type.chipped]
			apple_acacia = true
			cherry_acacia = true
			dead_acacia = true
			frosted_acacia = true
			golden_acacia = true
			golden_apple_acacia = true
			golden_cherry_acacia = true
			magenta_flower_acacia = true
			orange_acacia = true
			red_acacia = true
			white_flower_acacia = true
			apple_birch = true
			cherry_birch = true
			dead_birch = true
			frosted_birch = true
			golden_birch = true
			golden_apple_birch = true
			golden_cherry_birch = true
			magenta_flower_birch = true
			orange_birch = true
			red_birch = true
			white_flower_birch = true
			apple_dark_oak = true
			cherry_dark_oak = true
			dead_dark_oak = true
			frosted_dark_oak = true
			golden_dark_oak = true
			golden_apple_dark_oak = true
			golden_cherry_dark_oak = true
			magenta_flower_dark_oak = true
			orange_dark_oak = true
			red_dark_oak = true
			white_flower_dark_oak = true
			apple_jungle = true
			cherry_jungle = true
			dead_jungle = true
			frosted_jungle = true
			golden_jungle = true
			golden_apple_jungle = true
			golden_cherry_jungle = true
			magenta_flower_jungle = true
			orange_jungle = true
			red_jungle = true
			white_flower_jungle = true
			apple_oak = true
			cherry_oak = true
			dead_oak = true
			frosted_oak = true
			golden_oak = true
			golden_apple_oak = true
			golden_cherry_oak = true
			magenta_flower_oak = true
			orange_oak = true
			red_oak = true
			white_flower_oak = true
			apple_spruce = true
			cherry_spruce = true
			dead_spruce = true
			frosted_spruce = true
			golden_spruce = true
			golden_apple_spruce = true
			golden_cherry_spruce = true
			magenta_flower_spruce = true
			orange_spruce = true
			red_spruce = true
			white_flower_spruce = true

		[types.leaves_type.tconstruct]
			earth_slime = true
			sky_slime = true
			ender_slime = true

		[types.leaves_type.aether]
			skyroot = true
			golden_oak = true
			crystal = true
			crystal_fruit = true
			holiday = true
			decorated_holiday = true

		[types.leaves_type.deep_aether]
			roseroot = true
			flowering_roseroot = true
			blue_roseroot = true
			flowering_blue_roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.leaves_type.twilightforest]
			thorn = true
			beanstalk = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.autumnity]
			maple = true
			yellow_maple = true
			orange_maple = true
			red_maple = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.regions_unexplored]
			alpha = true
			apple_oak = true
			bamboo = true
			baobab = true
			blackwood = true
			magnolia = true
			cypress = true
			dead = true
			dead_pine = true
			eucalyptus = true
			flowering = true
			golden_larch = true
			kapok = true
			larch = true
			maple = true
			mauve = true
			orange_maple = true
			palm = true
			pine = true
			blue_magnolia = true
			pink_magnolia = true
			redwood = true
			red_maple = true
			brimwood = true
			enchanted_birch = true
			small_oak = true
			silver_birch = true
			socotra = true
			white_magnolia = true
			willow = true
			ashen = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.dungeonnowloading]
			azuro = true

		[types.leaves_type.the_great_outdoors]
			whitebark_pine = true

		[types.leaves_type.natures_spirit]
			frosty_redwood = true
			redwood = true
			sugi = true
			wisteria = true
			white_wisteria = true
			part_white_wisteria = true
			blue_wisteria = true
			part_blue_wisteria = true
			pink_wisteria = true
			part_pink_wisteria = true
			purple_wisteria = true
			part_purple_wisteria = true
			frosty_fir = true
			fir = true
			willow = true
			aspen = true
			yellow_aspen = true
			red_maple = true
			orange_maple = true
			yellow_maple = true
			cypress = true
			olive = true
			joshua = true
			ghaf = true
			palo_verde = true
			coconut = true
			cedar = true
			larch = true
			mahogany = true
			saxaul = true

	[types.cake]

		[types.cake.natures_spirit]
			cheese_block = true

		[types.cake.createaddition]
			chocolate_cake = true
			honey_cake = true

#Disables specific entries
[entries]

	[entries.stone_type]

		[entries.stone_type.chipped]
			tiled_column = true
			pillar = true
			checkered_tiles = true
			cracked_flat_tiles = true
			eroded = true
			weathered = true
			tiled_bordered = true
			simple_pillar = true
			scales = true
			smooth_column = true
			vertical_disordered_bricks = true
			fine_pillar = true
			sad = true
			brick_bordered = true
			glad = true
			smooth_inlayed = true
			unamused = true
			bordered = true
			cut_column = true
			edged_bricks = true
			cobbled = true
			smoothed_double_inlayed = true
			rounded_bricks = true
			overlapping_tiles = true
			pillar_top = true
			rough = true
			tiny_layered_bricks = true
			loded = true
			bricks = true
			massive_bricks = true
			layed_bricks = true
			spider_carving = true
			thick_inlayed = true
			tiny_brick_bordered = true
			pointed_dripstone = true
			sanded = true
			engraved = true
			offset_bricks = true
			small_bricks = true
			duh = true
			mini_tiles = true
			angry = true
			vertical_cut = true
			crying = true
			smooth_ringed = true
			runic_carved = true
			curly_pillar = true
			etched_bricks = true
			stacked_bricks = true
			spiraled = true
			inscribed = true
			polished = true
			cut_blank = true
			blank_carving = true
			prismal_remnants = true
			tiny_layered_slabs = true
			tiny_bricks = true
			flat_tiles = true
			inlayed = true
			trodden = true
			tiled = true
			creeper_carving = true
			cracked_bricks = true
			pillar_bricks = true
			cracked_disordered_bricks = true
			carved = true
			ornate_pillar = true

		[entries.stone_type.create]
			cut_wall = true
			small_bricks = true
			layered = true
			cut_brick_wall = true
			pillar = true
			cut_brick_stairs = true
			cut_brick_slab = true
			polished_cut_slab = true
			polished_cut_wall = true
			cut_slab = true
			small_brick_wall = true
			cut = true
			polished_cut = true
			small_brick_slab = true
			cut_stairs = true
			small_brick_stairs = true
			cut_bricks = true
			polished_cut_stairs = true

		[entries.stone_type.waystones]
			waystone = true

		[entries.stone_type.quark]
			polished_vertical_slab = true
			pillar = true
			vertical_slab = true

	[entries.mud_type]

		[entries.mud_type.quark]
			carved_bricks = true
			pillar = true
			brick_lattice = true

	[entries.wood_type]

		[entries.wood_type.chipped]
			fine_planks = true
			checkered_trapdoor = true
			overgrown_trapdoor = true
			overgrown_door = true
			windowed_door = true
			tiled_door = true
			classic_trapdoor = true
			circle_glass = true
			center_cut_log = true
			pegged_planks = true
			torch = true
			secret_door = true
			smooth_planks = true
			screen_door = true
			bared_glass = true
			ornate_bared_glass = true
			hewn_planks = true
			crossed_planks = true
			edged_stripped_log = true
			beach_door = true
			fine_vertical_planks = true
			cross_laced_planks = true
			diamond_bordered_glass = true
			railed_planks = true
			planks_mosaic = true
			distorted_trapdoor = true
			iron_barred_trapdoor = true
			firewood_log = true
			f_sign_stripped_log = true
			circle_glass_pane = true
			versailles_planks = true
			wise_stripped_log = true
			layered_stripped_log = true
			whirlwind_planks = true
			large_diamond_glass_pane = true
			planked_log = true
			mixed_log = true
			framed_planks = true
			square_glass = true
			vined_trapdoor = true
			barrel = true
			woven_glass = true
			detailed_planks = true
			woven_trapdoor = true
			cobweb_trapdoor = true
			gated_door = true
			supported_door = true
			barred_trapdoor = true
			line_bared_glass_pane = true
			horizontal_lined_glass_pane = true
			airy_trapdoor = true
			lumpy_stripped_log = true
			line_bared_glass = true
			slanted_planks = true
			edge_cut_log = true
			barred_door = true
			chipped_stripped_log = true
			patient_stripped_log = true
			suspicious_trapdoor = true
			herringbone_planks = true
			pressed_door = true
			planks_panel = true
			vertically_railed_planks = true
			bared_glass_pane = true
			diamond_bordered_glass_pane = true
			solid_trapdoor = true
			tiled_planks = true
			boarded_door = true
			dual_paneled_door = true
			square_glass_pane = true
			overgrown_log = true
			meshed_trapdoor = true
			thin_planks = true
			fancy_trapdoor = true
			paper_door = true
			warted_trapdoor = true
			basket_woven_planks = true
			enclosed_planks = true
			flowering_log = true
			k_sign_stripped_log = true
			double_herringbone_planks = true
			sign_stripped_log = true
			crated_planks = true
			knotted_stripped_log = true
			horizontal_lined_glass = true
			l_sign_stripped_log = true
			reinforced_log = true
			natural_planks = true
			classic_windowed_trapdoor = true
			brick_bond_planks = true
			wickered_planks = true
			bordered_glass_pane = true
			sliding_door = true
			heavy_trapdoor = true
			bordered_glass = true
			laced_planks = true
			boxed_planks = true
			reinforced_crate = true
			large_diamond_glass = true
			snowflake_glass_pane = true
			bricky_planks = true
			reinforced_stripped_log = true
			slotted_trapdoor = true
			bundled_log = true
			shack_door = true
			polished_planks = true
			ornate_bared_glass_pane = true
			stern_stripped_log = true
			diagonal_planks = true
			wall_torch = true
			crate = true
			nailed_planks = true
			cornered_planks = true
			shifted_planks = true
			vertical_planks = true
			glass_door = true
			fortified_door = true
			paneled_door = true
			carved_stripped_log = true
			leafy_trapdoor = true
			snowflake_glass = true
			heavy_door = true
			pointless_trapdoor = true
			stacked_planks = true
			planks_shavings = true
			i_sign_stripped_log = true
			twisted_trapdoor = true
			d_sign_stripped_log = true
			diamond_planks = true
			woven_glass_pane = true
			windowed_trapdoor = true
			tile_windowed_door = true
			damaged_log = true
			golden_barred_trapdoor = true
			nailed_log = true

		[entries.wood_type.valhelsia_structures]
			bundled_posts = true
			post = true
			bundled_stripped_posts = true
			cut_stripped_post = true
			stripped_post = true
			cut_post = true

		[entries.wood_type.valhelsia_furniture]
			hay_chair = true
			desk_drawer = true
			desk = true
			stool = true
			chair = true
			table = true

		[entries.wood_type.quark]
			vertical_planks = true
			ladder = true
			post = true
			trapped_chest = true
			vertical_slab = true
			chest = true
			hollow_log = true
			bookshelf = true
			stripped_post = true

		[entries.wood_type.regions_unexplored]
			branch = true

		[entries.wood_type.twilightforest]
			banister = true
			hollow_log_climbable = true
			hollow_log_horizontal = true
			hollow_log_vertical = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.create]
			window_pane = true
			window = true

	[entries.leaves_type]

		[entries.leaves_type.chipped]
			magenta_flower_leaves = true
			golden_leaves = true
			apple_leaves = true
			frosted_leaves = true
			orange_leaves = true
			red_leaves = true
			cherry_leaves = true
			golden_cherry_leaves = true
			dead_leaves = true
			golden_apple_leaves = true
			white_flower_leaves = true

		[entries.leaves_type.regions_unexplored]
			shrub = true

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

